import { Platform } from 'react-native';
import * as RNFS from 'react-native-fs';
import { KittenModel, normalizeModel } from './KittenModel';
import { CEPhonemizer } from './phonemizer/CEPhonemizer';
import type { KittenTTSConfig } from './KittenTTSConfig';
import type { KittenPhonemizerProtocol } from './phonemizer/types';
import { base64ToUint8Array } from './audio/Base64';

export interface KittenTTSBundledModelFiles {
  onnx: string;
  voices: string;
}

export interface KittenTTSBundledAssetsManifestV1 {
  version: 1;
  model: KittenModel | string;
  files: KittenTTSBundledModelFiles & {
    phonemizerRules: string;
    phonemizerList: string;
  };
}

export interface KittenTTSBundledAssetsManifestV2 {
  version: 2;
  defaultModel: KittenModel | string;
  models: Record<string, KittenTTSBundledModelFiles>;
  files: {
    phonemizerRules: string;
    phonemizerList: string;
  };
}

export type KittenTTSBundledAssetsManifest =
  | KittenTTSBundledAssetsManifestV1
  | KittenTTSBundledAssetsManifestV2;

export interface CreateBundledAssetConfigOptions
  extends Omit<KittenTTSConfig, 'model' | 'modelFiles' | 'phonemizer'> {
  /** Directory containing the files listed in the manifest. */
  basePath?: string;
  /** Native asset directory. Defaults to `kittentts`. */
  assetRoot?: string;
  /** Model to load from a multi-model manifest. Defaults to manifest.defaultModel. */
  model?: KittenModel | string;
  /** Override the default CEPhonemizer constructed from manifest paths. */
  phonemizer?: KittenPhonemizerProtocol;
}

/**
 * Create a KittenTTS config from the manifest generated by the CLI.
 *
 * The caller is responsible for passing a real filesystem directory. For
 * bundled app resources, copy them to an app-readable directory first if the
 * platform exposes them as APK/assets URIs instead of direct file paths.
 */
export async function createBundledAssetConfig(
  manifest: KittenTTSBundledAssetsManifest,
  options: CreateBundledAssetConfigOptions = {},
): Promise<KittenTTSConfig> {
  const {
    basePath,
    assetRoot = 'kittentts',
    model: selectedModel,
    phonemizer,
    ...rest
  } = options;
  const resolvedBasePath = basePath ? stripTrailingSlash(basePath) : '';
  const model = parseModel(selectedModel ?? defaultManifestModel(manifest));
  const modelFiles = manifestModelFiles(manifest, model);

  if (!basePath) {
    const [onnxData, voicesData, rulesText, listText] = await Promise.all([
      readBundledAssetBinary(assetRoot, modelFiles.onnx),
      readBundledAssetBinary(assetRoot, modelFiles.voices),
      readBundledAssetText(assetRoot, manifest.files.phonemizerRules),
      readBundledAssetText(assetRoot, manifest.files.phonemizerList),
    ]);

    return {
      ...rest,
      model,
      modelFiles: {
        onnxData,
        voicesData,
      },
      phonemizer: phonemizer ?? new CEPhonemizer({
        rulesText,
        listText,
      }),
    };
  }

  return {
    ...rest,
    model,
    modelFiles: {
      onnxPath: joinPath(resolvedBasePath, modelFiles.onnx),
      voicesPath: joinPath(resolvedBasePath, modelFiles.voices),
    },
    phonemizer: phonemizer ?? new CEPhonemizer({
      rulesPath: joinPath(resolvedBasePath, manifest.files.phonemizerRules),
      listPath: joinPath(resolvedBasePath, manifest.files.phonemizerList),
    }),
  };
}

async function readBundledAssetBinary(
  assetRoot: string,
  filePath: string,
): Promise<Uint8Array> {
  const base64 = Platform.OS === 'android'
    ? await RNFS.readFileAssets(joinPath(assetRoot, filePath), 'base64')
    : await RNFS.readFile(joinPath(joinPath(RNFS.MainBundlePath ?? '', assetRoot), filePath), 'base64');
  return base64ToUint8Array(base64);
}

async function readBundledAssetText(
  assetRoot: string,
  filePath: string,
): Promise<string> {
  return Platform.OS === 'android'
    ? RNFS.readFileAssets(joinPath(assetRoot, filePath), 'utf8')
    : RNFS.readFile(joinPath(joinPath(RNFS.MainBundlePath ?? '', assetRoot), filePath), 'utf8');
}

export function bundledAssetModels(
  manifest: KittenTTSBundledAssetsManifest,
): KittenModel[] {
  if (manifest.version === 1) return [parseModel(manifest.model)];
  return Object.keys(manifest.models).map(parseModel);
}

function defaultManifestModel(
  manifest: KittenTTSBundledAssetsManifest,
): KittenModel | string {
  return manifest.version === 1 ? manifest.model : manifest.defaultModel;
}

function manifestModelFiles(
  manifest: KittenTTSBundledAssetsManifest,
  model: KittenModel,
): KittenTTSBundledModelFiles {
  if (manifest.version === 1) {
    if (parseModel(manifest.model) !== model) {
      throw new Error(`Model ${model} is not present in bundled assets manifest.`);
    }
    return manifest.files;
  }

  const files = manifest.models[model];
  if (!files) {
    throw new Error(`Model ${model} is not present in bundled assets manifest.`);
  }
  return files;
}

function parseModel(model: KittenModel | string): KittenModel {
  try {
    return normalizeModel(model as never);
  } catch {
    throw new Error(`Unknown KittenTTS model in bundled assets manifest: ${model}`);
  }
}

function joinPath(basePath: string, filePath: string): string {
  if (!basePath) return filePath;
  return `${basePath}/${stripLeadingSlash(filePath)}`;
}

function stripLeadingSlash(filePath: string): string {
  return filePath.replace(/^\/+/, '');
}

function stripTrailingSlash(filePath: string): string {
  return filePath.replace(/\/+$/, '');
}
