import { KittenModel, normalizeModel } from './KittenModel';
import { CEPhonemizer } from './phonemizer/CEPhonemizer.web';
import type { KittenTTSConfig } from './KittenTTSConfig.web';
import type { KittenPhonemizerProtocol } from './phonemizer/types';

export interface KittenTTSBundledModelFiles {
  onnx: string;
  voices: string;
}

export interface KittenTTSBundledAssetsManifestV1 {
  version: 1;
  model: KittenModel | string;
  files: KittenTTSBundledModelFiles & {
    phonemizerRules: string;
    phonemizerList: string;
  };
}

export interface KittenTTSBundledAssetsManifestV2 {
  version: 2;
  defaultModel: KittenModel | string;
  models: Record<string, KittenTTSBundledModelFiles>;
  files: {
    phonemizerRules: string;
    phonemizerList: string;
  };
}

export type KittenTTSBundledAssetsManifest =
  | KittenTTSBundledAssetsManifestV1
  | KittenTTSBundledAssetsManifestV2;

export interface CreateBundledAssetConfigOptions
  extends Omit<KittenTTSConfig, 'model' | 'modelFiles' | 'phonemizer'> {
  /** Directory or URL prefix containing the files listed in the manifest. */
  basePath?: string;
  /** Browser asset directory. Defaults to `kittentts`. */
  assetRoot?: string;
  /** Model to load from a multi-model manifest. Defaults to manifest.defaultModel. */
  model?: KittenModel | string;
  /** Override the default CEPhonemizer constructed from manifest text. */
  phonemizer?: KittenPhonemizerProtocol;
}

/**
 * Create a KittenTTS web config from the manifest generated by the CLI.
 *
 * Browser builds fetch asset bytes from `basePath` when provided, otherwise
 * from `assetRoot`. The returned config uses in-memory model bytes so bundlers
 * do not need filesystem access.
 */
export async function createBundledAssetConfig(
  manifest: KittenTTSBundledAssetsManifest,
  options: CreateBundledAssetConfigOptions = {},
): Promise<KittenTTSConfig> {
  const {
    basePath,
    assetRoot = 'kittentts',
    model: selectedModel,
    phonemizer,
    ...rest
  } = options;
  const root = stripTrailingSlash(basePath ?? assetRoot);
  const model = parseModel(selectedModel ?? defaultManifestModel(manifest));
  const modelFiles = manifestModelFiles(manifest, model);

  const [onnxData, voicesData, rulesText, listText] = await Promise.all([
    readBundledAssetBinary(root, modelFiles.onnx),
    readBundledAssetBinary(root, modelFiles.voices),
    readBundledAssetText(root, manifest.files.phonemizerRules),
    readBundledAssetText(root, manifest.files.phonemizerList),
  ]);

  return {
    ...rest,
    model,
    modelFiles: {
      onnxData,
      voicesData,
    },
    phonemizer: phonemizer ?? new CEPhonemizer({
      rulesText,
      listText,
    }),
  };
}

async function readBundledAssetBinary(
  root: string,
  filePath: string,
): Promise<Uint8Array> {
  const response = await fetch(joinPath(root, filePath));
  if (!response.ok) {
    throw new Error(`HTTP ${response.status} loading bundled asset ${filePath}`);
  }
  return new Uint8Array(await response.arrayBuffer());
}

async function readBundledAssetText(
  root: string,
  filePath: string,
): Promise<string> {
  const response = await fetch(joinPath(root, filePath));
  if (!response.ok) {
    throw new Error(`HTTP ${response.status} loading bundled asset ${filePath}`);
  }
  return response.text();
}

export function bundledAssetModels(
  manifest: KittenTTSBundledAssetsManifest,
): KittenModel[] {
  if (manifest.version === 1) return [parseModel(manifest.model)];
  return Object.keys(manifest.models).map(parseModel);
}

function defaultManifestModel(
  manifest: KittenTTSBundledAssetsManifest,
): KittenModel | string {
  return manifest.version === 1 ? manifest.model : manifest.defaultModel;
}

function manifestModelFiles(
  manifest: KittenTTSBundledAssetsManifest,
  model: KittenModel,
): KittenTTSBundledModelFiles {
  if (manifest.version === 1) {
    if (parseModel(manifest.model) !== model) {
      throw new Error(`Model ${model} is not present in bundled assets manifest.`);
    }
    return manifest.files;
  }

  const files = manifest.models[model];
  if (!files) {
    throw new Error(`Model ${model} is not present in bundled assets manifest.`);
  }
  return files;
}

function parseModel(model: KittenModel | string): KittenModel {
  try {
    return normalizeModel(model as never);
  } catch {
    throw new Error(`Unknown KittenTTS model in bundled assets manifest: ${model}`);
  }
}

function joinPath(basePath: string, filePath: string): string {
  if (!basePath) return filePath;
  return `${basePath}/${stripLeadingSlash(filePath)}`;
}

function stripLeadingSlash(filePath: string): string {
  return filePath.replace(/^\/+/, '');
}

function stripTrailingSlash(filePath: string): string {
  return filePath.replace(/\/+$/, '');
}
